### ISSUE TITLE
Samba AD DC

### ISSUE THREAD

**Issue by DrEVILish** [pitkley/dockerfiles#1]
Good Evening,
I'm running my DC on my synology docker container.

From both my Win10 (joined) and macOS (unjoined) instances I try to connect to the domain sysvol or netlogon shares and receive:
macOS: You do not have permission to access this server.
Win10: \xxxxxxx.com\sysvol is unavaliable. etc... error

I have set 
SAMBA_REALM: xxxxxxxxxx.com
SAMBA_PASSWORD: *****
SAMBA_DNS_FORWARDER: 8.8.8.8
SAMBA_OPTIONS: --use-ntvfs

Is there anything else I need to run or set for this to work correctly.

Using RSAT I have been able to access DNS Manager, Users & Computers screen. There isn't a problem with talking to the network it's on. Just accessing those particular volumes.

I have my volumes set to:
/var/lib/samba RW -> my databases folder for SAMBA stuff
/etc/localtime RO -> my synologys /etc/localtime file for time sync.

**Comment by twist2k** [comment]
Did you ever figure this out? I am currently running DSM 6 and was looking to try this same setup, I did read it will be coming out with DSM 6.1 which is awesome, but I need to get this functionality up sooner then later.
